source ./base_img.conf
source ./base_img.sh

IF_ROOT
PRE_INST
COMMON $PKG
CREATE_DIR $WORK_DIR $DOWN_BASE $FOLDER_BUILD_FS $FOLDER_BUILD_ISO $CASPER_DIR $ISOLINUX_DIR $OUTPUT_ISO $OUTPUT_ISO_FILE
DOWN_FS
MAKE_FS $IGNORE_DIR 
CREATE_TREE_ISO
BUILD_ISO $OUTPUT_ISO/$OUTPUT_ISO_NAME $FOLDER_BUILD_ISO
POST_BUILD